name: ghpages
on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev ghostscript poppler-utils
        if: ${{ runner.os == 'Linux' }}

      - name: Generate
        run: |
          ./build.sh
          cp index.html out/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./out

  publish-ghpages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
